FoodDelivery_FinalProject/Wolt/Wolt/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Service.Services.Interfaces;
using Service.ViewModels.Home;
using Service.ViewModels.Slider;

namespace Wolt.Controllers
{
    public class HomeController : Controller
    {
        private readonly ISliderService _sliderService;
        private readonly IRestaurantService _restaurantService;
        private readonly IBrandService _brandService;

        public HomeController(ISliderService sliderService, IRestaurantService restaurantService, IBrandService brandService)
        {
            _sliderService = sliderService;
            _restaurantService = restaurantService;
            _brandService = brandService;
        }
        public async Task<IActionResult> Index()
        {
            var sliders = await _sliderService.GetAllAsync();
            var restaurants = await _restaurantService.GetAllAsync();
            var brands = await _brandService.GetAllAsync();

            var homeVM = new HomeVM
            {
                Sliders = sliders,
                Restaurants = restaurants,
                Brands = brands,
            };

            return View(homeVM);
        }

        [HttpGet]
        public async Task<IActionResult> Search(string query)
        {
            var results = await _restaurantService.SearchRestaurantsAsync(query);
            return View("Search", results);
        }
    }
}

FoodDelivery_FinalProject/Wolt/Wolt/Controllers/MenuController.cs
using Domain.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Service.Services;
using Service.Services.Interfaces;
using Service.ViewModels.Menu;
using Service.ViewModels.MenuCategory;
using Service.ViewModels.MenuItem;
using Service.ViewModels.Restaurant;
using Service.ViewModels.RestaurantReview;

namespace Wolt.Controllers
{
    [Authorize(Roles = "Customer, Admin")]
    public class MenuController : Controller
    {
        private readonly IRestaurantService _restaurantService;
        private readonly IMenuItemService _menuItemService;
        private readonly IMenuCategoryService _menuCategoryService;
        private readonly IRestaurantReviewService _restaurantReviewService;
        private readonly IAccountService _accountService;
        private readonly ICustomerService _customerService; 

        public MenuController(IRestaurantService restaurantService,
                              IMenuItemService menuItemService,
                              IMenuCategoryService menuCategoryService,
                              IRestaurantReviewService restaurantReviewService,
                              IAccountService accountService,
                              ICustomerService customerService)
        {
            _restaurantService = restaurantService;
            _menuItemService = menuItemService;
            _menuCategoryService = menuCategoryService;
            _restaurantReviewService = restaurantReviewService;
            _accountService = accountService;
            _customerService = customerService;
        }


        public async Task<IActionResult> Index(int restaurantId)
        {
            var menuItems = await _menuItemService.GetByRestaurantIdAsync(restaurantId);
            var menuCategories = await _menuCategoryService.GetByRestaurantIdAsync(restaurantId);
            var restaurant = await _restaurantService.GetByIdAsync(restaurantId);
            var reviews = await _restaurantReviewService.GetAllByRestaurantIdAsync(restaurantId);
            var currentUser = await _accountService.GetCurrentUserAsync();

            int? currentCustomerId = null;
            if (currentUser != null)
            {
                var customer = await _customerService.GetByUserIdAsync(currentUser.Id);
                currentCustomerId = customer?.Id;
            }

            ViewBag.CurrentCustomerId = currentCustomerId;

            var viewModel = new MenuVM
            {
                MenuItems = menuItems.Select(mi => new MenuItemVM
                {
                    Id = mi.Id,
                    Name = mi.Name,
                    Description = mi.Description,
                    Price = mi.Price,
                    CategoryName = mi.MenuItemCategory?.Name,
                    CategoryId = mi.CategoryId,
                    Image = mi.Image,
                    DiscountedPrice = mi.DiscountedPrice,

                }),

                MenuCategories = menuCategories.Select(c => new MenuCategoryVM
                {
                    Id = c.Id,
                    Name = c.Name
                }),

                Restaurant = new RestaurantVM
                {
                    Id = restaurant.Id,
                    Name = restaurant.Name,
                    Address = restaurant.Address,
                    Phone = restaurant.Phone,
                    Image = restaurant.Image,
                    EstimatedDeliveryTime = restaurant.EstimatedDeliveryTime,
                    DeliveryCost = restaurant.DeliveryCost,
                    CategoryName = restaurant.CategoryName,
                    RestaurantCategoryId = restaurant.RestaurantCategoryId,
                    AverageRating = restaurant.AverageRating
                },

                RestaurantReviews = reviews.Select(r => new RestaurantReviewVM
                {
                    RestaurantId = r.RestaurantId,
                    Comment = r.Comment,
                    Rating = r.Rating,
                    CustomerName = r.Customer?.User?.FullName,
                    Id = r.Id,
                    CustomerId = r.CustomerId,
                }),

                RestaurantReviewCreate = new RestaurantReviewCreateVM
                {
                    RestaurantId = restaurantId,
                }
            };

            return View(viewModel);
        }

    }
}

FoodDelivery_FinalProject/Wolt/Wolt/Controllers/RestaurantController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Service.Services;
using Service.Services.Interfaces;
using Service.ViewModels.Home;
using Service.ViewModels.Restaurant;

namespace Wolt.Controllers
{
    [Authorize(Roles = "Customer, Admin")]
    public class RestaurantController : Controller
    {
        private readonly IRestaurantService _restaurantService;
        private readonly IRestaurantCategoryService _restaurantCategoryService;

        public RestaurantController(IRestaurantService restaurantService,
                                    IRestaurantCategoryService restaurantCategoryService)
        {
            _restaurantService = restaurantService;
            _restaurantCategoryService = restaurantCategoryService;
        }
        public async Task<IActionResult> Index(int page = 1)
        {
            var vm = await _restaurantService.GetAllPaginatedWithCategories(page);
            return View(vm);
        }

        public async Task<IActionResult> GetRestaurantsPage(int page = 1)
        {
            var vm = await _restaurantService.GetAllPaginatedWithCategories(page);
            return PartialView("_RestaurantsListPartial", vm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Filter(RestaurantFilterVM filter)
        {
            var filteredRestaurants = await _restaurantService.GetFilteredAsync(filter);
            return PartialView("_FilteredRestaurantsPartial", filteredRestaurants);
        }

        [HttpGet]
        public async Task<IActionResult> GetSortedRestaurants(string sortOrder = "newest", int page = 1)
        {
            var allRestaurants = await _restaurantService.GetAllPaginatedWithCategories(page);
            var sorted = SortRestaurants(allRestaurants.Restaurants, sortOrder);

            allRestaurants.Restaurants = sorted.ToList();

            return PartialView("_RestaurantsListPartial", allRestaurants);
        }

        private IEnumerable<RestaurantVM> SortRestaurants(IEnumerable<RestaurantVM> list, string sortOrder)
        {
            return sortOrder switch
            {
                "newest" => list.OrderByDescending(r => r.Id),
                "oldest" => list.OrderBy(r => r.Id),
                "name_asc" => list.OrderBy(r => r.Name),
                "name_desc" => list.OrderByDescending(r => r.Name),
                "rating_high" => list.OrderByDescending(r => r.AverageRating),
                "rating_low" => list.OrderBy(r => r.AverageRating),
                _ => list.OrderByDescending(r => r.Id)
            };
        }

    }
}

FoodDelivery_FinalProject/Wolt/Wolt/Views/Home/Index.cshtml
@model HomeVM

@section Styles {
    <link rel="stylesheet" href="~/assets/css/home.css" />
}


<main>
    <section id="offers-slider" class="position-relative overflow-hidden">
        <div class="container-fluid">
            <div class="row flex-nowrap transition" id="slider-row">
                @foreach(var slider in Model.Sliders)
                {
                    <div class="col-12 col-sm-12 col-md-6 col-xl-6 image-item">
                        <img src="assets/images/@slider.Image" class="img-fluid rounded">
                    </div>
                } 
            </div>
        </div>

        <div class="arrows position-absolute w-100 d-flex justify-content-between px-3"
             style="top: 50%; transform: translateY(-50%);">
            <div class="left-arrow d-flex align-items-center justify-content-center bg-dark text-info rounded-circle"
                 style="width: 40px; height: 40px; cursor: pointer;">
                <i class="fa-solid fa-arrow-left"></i>
            </div>
            <div class="right-arrow d-flex align-items-center justify-content-center bg-dark text-info rounded-circle"
                 style="width: 40px; height: 40px; cursor: pointer;">
                <i class="fa-solid fa-arrow-right"></i>
            </div>
        </div>
    </section>

    <section id="info">
        <div class="container">
            <div class="row">
                <div class="col-12 col-sm-12 col-md-12 col-lg-4 col-xl-4">
                    <div class="info-card">
                        <div class="content">
                            <i class="fa-solid fa-utensils"></i>
                            <h4>Quality food</h4>
                            <p>
                                Lorem ipsum, dolor sit amet consectetur adipisicing elit. Veritatis incidunt unde
                                aliquid minima sint quibusdam!
                            </p>
                        </div>
                    </div>

                </div>
                <div class="col-12 col-sm-12 col-md-12 col-lg-4 col-xl-4">
                    <div class="info-card">
                        <div class="content">
                            <i class="fa-solid fa-cart-shopping"></i>
                            <h4>Online delivery</h4>
                            <p>
                                Lorem ipsum, dolor sit amet consectetur adipisicing elit. Veritatis incidunt unde
                                aliquid minima sint quibusdam!
                            </p>

                        </div>
                    </div>

                </div>
                <div class="col-12 col-sm-12 col-md-12 col-lg-4 col-xl-4">
                    <div class="info-card">
                        <div class="content">
                            <i class="fa fa-3x fa-headset"></i>
                            <h4>24/7 Service</h4>
                            <p>
                                Lorem ipsum, dolor sit amet consectetur adipisicing elit. Veritatis incidunt unde
                                aliquid minima sint quibusdam!
                            </p>

                        </div>
                    </div>
                </div>
            </div>
        </div>

    </section>

    <section id="popular-restaurants">
        <h1>Populyar Restoranlar</h1>
        <div class="container">
            <div class="row">
                @foreach(var restaurant in Model.Restaurants.Take(8))
                {
                    <div class="col-6 col-sm-6 col-md-6 col-lg-3 col-xl-3">
                        <div class="restaurant-card">
                            <div class="image">
                                <a href="@Url.Action("Index", "Menu", new { restaurantId = restaurant.Id })"><img src="assets/images/@restaurant.Image"></a>
                            </div>
                            <div class="content">
                                <div class="res-cat">
                                    <h5 style="margin-left:9px; font-weight:bold;">@restaurant.Name</h5>
                                    <p style="margin-left:9px">@restaurant.CategoryName</p>
                                </div>
                                <div class="rating" style="margin-top:13px">
                                    <span><i class="fa-solid fa-star"></i> 5</span>
                                </div>
                            </div>
                        </div>
                    </div>
                }

            </div>

        </div>
        <a asp-controller="Restaurant" asp-action="Index" style="list-style:none; text-decoration:none;">
            <div class="more-button text-center mt-4">
                <button class="btn-more">
                    Daha çox <i class="fa-solid fa-chevron-right"></i>
                </button>
            </div>
        </a>
       
    </section>

    <section id="brands">
        <div class="brands-arrows">
            <h1>Brendlər</h1>
            <div class="arrows position-absolute w-100 d-flex justify-content-between">
                <div class="left-arrow d-flex align-items-center justify-content-center bg-dark text-info rounded-circle"
                     style="width: 40px; height: 40px; cursor: pointer;">
                    <i class="fa-solid fa-arrow-left"></i>
                </div>
                <div class="right-arrow d-flex align-items-center justify-content-center bg-dark text-info rounded-circle"
                     style="width: 40px; height: 40px; cursor: pointer;">
                    <i class="fa-solid fa-arrow-right"></i>
                </div>
            </div>
        </div>

        <div id="brands-slider" class="container-fluid overflow-hidden">
            <div class="row flex-nowrap transition" id="brands-row">
                @foreach (var brand in Model.Brands)
                {
                    <div class="col-6 col-sm-6 col-md-4 col-lg-2 col-xl-2 image-item">
                        <div class="image">
                            <img src="~/assets/images/@brand.Image" class="img-fluid">
                        </div>
                    </div>

                }
            </div>
        </div>
    </section>

</main>


@section Scripts {
    <script src="~/assets/js/home.js" asp-append-version="true"></script>
}

FoodDelivery_FinalProject/Wolt/Wolt/Views/Home/Search.cshtml
@model IEnumerable<RestaurantVM>

@* @section Styles {
    <link rel="stylesheet" href="~/assets/css/home.css" />
} *@

<main>
    <section id="search-results">
        <div class="container">
            <h2 class="text-center mt-4">Axtarış nəticələri</h2>

            @if (!Model.Any())
            {
                <p class="text-center mt-3 text-danger">Nəticə tapılmadı.</p>
            }
            else
            {
                <div class="row mt-4">
                    @foreach (var restaurant in Model)
                    {
                        <div class="col-3 col-sm-6 col-md-4 col-lg-3 col-xl-3">
                            <div class="restaurant-card">
                                <div class="image">
                                    <a asp-controller="Restaurant" asp-action="Detail" asp-route-id="@restaurant.Id">
                                        <img src="~/assets/images/@restaurant.Image" class="img-fluid rounded" />
                                    </a>
                                </div>
                                <div class="content">
                                    <div class="res-cat">
                                        <h5 style="margin-left:9px; font-weight:bold;">@restaurant.Name</h5>
                                        <p style="margin-left:9px">@restaurant.CategoryName</p>
                                    </div>
                                    <div class="rating" style="margin-top:13px">
                                        <span><i class="fa-solid fa-star"></i> 5</span>
                                    </div>
                                </div>
                            </div>
                        </div>
                    }
                </div>
            }
        </div>
    </section>
</main>


<style>
    html, body {
        height: 100%;
        margin: 0;
        padding: 0;
    }

    body {
        display: flex;
        flex-direction: column;
        min-height: 100vh; /* full viewport height */
    }

    main {
        flex: 1; /* take all remaining space */
    }
    h2 {
        color: white;
        text-align: center;
        transform: translateY(20px);
    }

    .restaurant-card {
        margin-top: 40px;
        width: 280px; /* slightly smaller width */
        height: auto; /* let height be automatic based on content */
        border: 1px solid rgba(255, 255, 255, 0.1); /* lighter border */
        background-color: #1a1a1a;
        border-radius: 12px;
        overflow: hidden;
        box-shadow: 0 4px 12px rgba(255, 255, 255, 0.05);
        transition: transform 0.3s ease, box-shadow 0.3s ease;
        margin-bottom: 25px;
        color: #fff;
        display: flex;
        flex-direction: column;
    }

        .restaurant-card:hover {
            transform: translateY(-8px);
            box-shadow: 0 0 20px rgba(0, 157, 224, 0.6);
        }

        .restaurant-card .image img {
            width: 100%;
            height: 160px; /* slightly smaller image height */
            object-fit: cover;
            display: block;
            border-top-left-radius: 12px;
            border-top-right-radius: 12px;
        }

        .restaurant-card .content {
            display: flex;
            justify-content: space-between;
            align-items: center;
            padding: 15px 20px;
            color: #fff;
            /* removed transform, unnecessary here */
            flex-grow: 1;
        }

            .restaurant-card .content .res-cat {
                flex-grow: 1;
            }

            .restaurant-card .content h5 {
                margin: 0 0 5px 0;
                font-weight: 700;
                font-size: 1.1rem;
            }

            .restaurant-card .content p {
                margin: 0;
                font-size: 0.9rem;
                color: #bbb;
            }

            .restaurant-card .content .rating {
                margin-left: 10px;
                white-space: nowrap;
            }

                .restaurant-card .content .rating span {
                    display: inline-block;
                    background-color: #009de0;
                    padding: 5px 12px;
                    border-radius: 12px;
                    font-size: 0.85rem;
                    color: #fff;
                    font-weight: 600;
                }

                .restaurant-card .content .rating i {
                    color: #ffd700;
                    margin-right: 6px;
                }


</style>